spring:
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          format_sql: true

  datasource:
    url: jdbc:postgresql://localhost:30001/postgres
    username: postgres
    password: Y9Fn7HQCa4

  jta:
    atomikos:
      connectionfactory:
        max-pool-size: 3
      datasource:
        max-pool-size: 3

#logging.level.org.hibernate.SQL=DEBUG

#logging.level.root=DEBUG
#logging.level.com.atomikos=DEBUG


ibm:
  mq:
    queueManager: ibmmq
    channel: DEV.ADMIN.SVRCONN
    connName: localhost(32501)
    user: admin
    password: passw0rd
