spring:
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          format_sql: true

  datasource:
    url: jdbc:postgresql://localhost:30001/postgres
    username: postgres
    password: Yx9IQNt2CV

  jta:
    atomikos:
      connectionfactory:
        max-pool-size: 3
      datasource:
        max-pool-size: 3

#logging:
#  level:
#    root: DEBUG
#    com.atomikos: DEBUG
#    org.hibernate.SQL: DEBUG


ibm:
  mq:
    queueManager: ibmmq
    channel: DEV.ADMIN.SVRCONN
    connName: localhost(32501)
    user: admin
    password: passw0rd
